"""change_streamers_profiles_and_more

Revision ID: 0004
Revises: 0003
Create Date: 2025-11-30 22:07:13.546635

"""

from collections.abc import Sequence

import fastapi_storages
import sqlalchemy as sa
from alembic import op

from models.streamers import avatars_storage

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streamers_profiles",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("force_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("avatar", fastapi_storages.integrations.sqlalchemy.ImageType(storage=avatars_storage), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "viewers_profiles",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "streamers_marks",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("viewer_id", sa.Integer(), nullable=False),
        sa.Column("streamer_id", sa.Integer(), nullable=False),
        sa.Column("mark", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["streamer_id"], ["streamers_profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["viewer_id"], ["viewers_profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("streamer_id", "viewer_id"),
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table("streamers_marks")
    op.drop_table("viewers_profiles")
    op.drop_table("streamers_profiles")
    # ### end Alembic commands ###
