"""change_streamers_marks_and_more

Revision ID: 0004
Revises: 0003
Create Date: 2025-11-26 11:00:27.517146

"""

from collections.abc import Sequence

import fastapi_storages
import sqlalchemy as sa
from alembic import op
from fastapi_storages import FileSystemStorage

from settings.conf import settings

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streamers_marks",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("streamer_id", sa.Integer(), nullable=False),
        sa.Column("mark", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["streamer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("streamer_id", "user_id"),
    )
    op.create_table(
        "streamers_profiles",
        sa.Column(
            "avatar",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=FileSystemStorage(path=settings.local_storage_path)
            ),
            nullable=True,
        ),
        sa.Column("force_rating", sa.Float(precision=2), nullable=True),
        sa.Column("force_rating_votes", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("streamers_profiles")
    op.drop_table("streamers_marks")
    # ### end Alembic commands ###
